add_lunch_combo angler-userdebug
add_lunch_combo bullhead-userdebug
add_lunch_combo shamu-userdebug
add_lunch_combo aosp_d6603-userdebug
add_lunch_combo aosp_e6653-userdebug
add_lunch_combo aosp_e6683-userdebug